【issue18】シェフのcrud api作成、swagger作成
qin-team-recipe/11-recipe-api pull request #20
Opened 2023-06-25 10:02 UTC by ryutaroda

## 変更内容

- chef
  - CRUD API
  - swagger
    - swaggerをroutesに書いてみました。それに伴い下記内容の変更
      - controllerの書き方を変更。
      - routes.tsとコントローラー名のroutes.tsにswagger記述
      - コントローラー名のroutes.tsにrouteを指定(これまではコントローラーへ直に指定していました)
- requestbody取得のためライブラリ追加

## その他

- テストがなくてもダミーデータを使用してPOSTMANで確認ができそうです。なので一通りできて余裕があればテストするというのはどうでしょうか？

## 解決する issue

- close #18

2023-06-27 16:16 UTC, ysm0706glee requested changes
いくつかコメントさせていただきました！僕がわかっていないだけかもですのでおっしえていただきたいです🙇‍♂️

2023-06-27 16:16 UTC, ysm0706glee commented on prisma/prisma-client.ts
型めっちゃ良いですね！

2023-06-27 16:16 UTC, ysm0706glee commented on src/index.ts
> +import bodyParser from "body-parser";
僕はapp.use(express.json());でいけました🤔

`app.use(express.json());`

2023-06-27 16:16 UTC, ysm0706glee commented on src/controllers/chef.controller.ts
> +      userId: string | null;
userIdは自動だと思うのでいらない気がします🤔

2023-06-27 16:16 UTC, ysm0706glee commented on src/controllers/chef.controller.ts
> +    const { role } = req.query;
roleの意味ありますでしょうか？
`await prisma.chef.findMany();`
で絶対chefs返ってくると思ったのですが...

2023-06-27 16:16 UTC, ysm0706glee commented on src/controllers/chef.controller.ts
> +      userId: string | null;
上記と同じ

2023-06-28 01:07 UTC, ryutaroda commented on src/index.ts
> +import bodyParser from "body-parser";
もう一度確認してみます！
どの部分にコードを追加したか教えていただけますか？

2023-06-28 01:11 UTC, ryutaroda commented on src/controllers/chef.controller.ts
> +      userId: string | null;
マイレシピの登録できるユーザーは、usersテーブルを作成→chefsテーブルを作成の順番を想定しているので、
usersテーブルのidをuserIdに入れる必要があります。

2023-06-28 01:15 UTC, ryutaroda commented on src/controllers/chef.controller.ts
> +    const { role } = req.query;
シェフ一覧ではroleがCHEFのものを取得する必要があるため、すべて取得、roleによる絞り込みも可能にしました。
roleがUSERのものだけを一覧で取得する機会があるかわからないので、roleでのパラメータをなくしてrole=CHEFの固定でも良いかもしれないですね！

2023-06-28 17:54 UTC, ysm0706glee approved these changes
1点質問させていただいたのですがそこがokそうであればマージお願いします！
https://github.com/qin-team-recipe/11-recipe-api/pull/20#discussion_r1244846417

2023-06-28 17:54 UTC, ysm0706glee commented on src/controllers/chef.controller.ts
> +      userId: string | null;
なるほど！教えていただきありがとうございます！
では
`userId: string | null;`
ではなく
`userId: string;`
ですかね？？
そして
```
    if (!name || !role) {
      res.status(400).json({ message: "Name, and role are required" });
```
にも!userIdがあった方が良い気がします

2023-06-28 17:54 UTC, ysm0706glee commented on src/controllers/chef.controller.ts
> +    const { role } = req.query;
教えていただきありがとうございます！そうですね、関数名がgetChefsですのでこの関数ではシェフだけ返すで良さそうな気がします！

2023-06-29 00:08 UTC, ryutaroda commented on src/controllers/chef.controller.ts
> +      userId: string | null;
シェフのroleの違いは以下です。

Chef（ユーザー
- role = ‘USER’
- userIdにUserのid(Userモデルを持つ）

Chef（シェフ
- role = ‘CHEF’
- userIdはnull（認証の必要がないためUserモデルなし）

なのでuserIdにnullは許容する想定です。
厳密にはroleがUSERの場合userIdは必須ですね。
以下の内容で修正しました。
```
if (!name || !role) {
      if (role === "USER" && !userId) {
        res.status(400).json({ message: "Name, and role and userId are required" });
        return;
      }
      res.status(400).json({ message: "Name, and role are required" });
      return;
    }
```

2023-06-29 06:04 UTC, ysm0706glee approved these changes
LGTM!

2023-06-29 06:04 UTC, merged