Recipe api
qin-team-recipe/11-recipe-api pull request #22
Opened 2023-07-01 14:18 UTC by ysm0706glee

## 変更内容
レシピ一覧、レシピ収得、レシピ作成のapi作成

- 変更内容記載

## その他

## 解決する issue

- close #21

2023-07-01 16:38 UTC, ryutaroda approved these changes
@ysm0706glee 
動作問題ありません！

2023-07-01 16:38 UTC, ryutaroda commented on src/controllers/recipe.controller.ts
> +type CreateRecipeBody = {
@ysm0706glee 
typeはこういう書き方をするんですね！
参考に次作成してみます！chefのところも修正します！

2023-07-04 11:55 UTC, aguriken requested changes

2023-07-04 11:55 UTC, aguriken commented on src/routes/routes.ts
> + *         - servingSize
DBのカラム名はスネークケースなのでスネークケースの方が良いのかと思います！

2023-07-04 11:55 UTC, aguriken commented on src/routes/routes.ts
> + *         chefId:
スネークケースの方が良いかと！

2023-07-04 11:55 UTC, aguriken commented on src/routes/routes.ts
> + *         servingSize:
スネークケースの方が良いかと！

2023-07-04 11:56 UTC, merged

2023-07-04 11:57 UTC, aguriken commented
@ysm0706glee 
進めるためにmergeしました！また上記コメント別Issueで作成いただければ！